### ISSUE TITLE
Add quaternions

### ISSUE THREAD

**Issue by mgold** [johnpmayer/elm-linear-algebra#9]
My long-term goal is to implement an easily-deployed [trackball](http://threejs.org/examples/#misc_controls_trackball), copying heavily from three.js. Part of the implementation involves multiplying a vector by a quaternion, so I figure, why not put it all in one place?

If you're okay adding this, I can do some of the legwork, but it seems the relevant code is [here](https://github.com/mrdoob/three.js/blob/9c30286b38df039fca389989ff06ea1c15d6bad1/src/math/Quaternion.js) and [here](https://github.com/mrdoob/three.js/blob/9c30286b38df039fca389989ff06ea1c15d6bad1/src/math/Vector3.js#L280-L306). Thoughts?

**Comment by TheSeamau5** [comment]
The best bet would probably be to simply alias `Vector4` and add the quaternion operations on top of that.

**Comment by mgold** [comment]
I can look into that, good idea!
